### PR TITLE
Feature/#131 add popup view

### PR DESCRIPTION
**Pull request by vaxul**
# New Popup View

‼ Before the first try make sure to backup your existing tab groups.

## Showcase
Here a little video to show this new view in action:
[VIDEO: video-showcase.zip](https://github.com/projectdelphai/panorama-tab-groups/files/3918576/video-showcase.zip)

### Groups Frame
- [x] Quick search trough all group URLs and titles. [Screenshot](https://user-images.githubusercontent.com/3798226/69832716-1f3c5800-1230-11ea-91cd-22007f260acc.png)
- [x] Quick access to the first tab from a group. [Screenshot](https://user-images.githubusercontent.com/3798226/69832712-1ea3c180-1230-11ea-927e-321ed174c55f.png)
- [x] Allow adding of a new group. [Screenshot](https://user-images.githubusercontent.com/3798226/69850438-8af9e180-127f-11ea-92ec-bbb467178bb8.png)
- [x] Allow removing of a group. [Screenshot](https://user-images.githubusercontent.com/3798226/69832702-1e0b2b00-1230-11ea-81bc-4ae490979a85.png)
- [x] Direct access to the settings. [Screenshot](https://user-images.githubusercontent.com/3798226/69832713-1f3c5800-1230-11ea-9f2d-696ed0a77db1.png)
- [x] Allow sorting of groups with drag&drop. [Screenshot](https://user-images.githubusercontent.com/3798226/69832707-1ea3c180-1230-11ea-8a27-5035c854ae49.png)
- [x] Show current active group in list. [Screenshot](https://user-images.githubusercontent.com/3798226/69784953-5884b180-11b7-11ea-82d2-2d4348dbb4ae.png)
- [x] Show number of  tabs in a groups with acces to group details frame. [Screenshot](https://user-images.githubusercontent.com/3798226/69832705-1e0b2b00-1230-11ea-8d6d-497c70276ca8.png)

### Group Detail Frame
- [x] Allow editing of the group name. [Screenshot](https://user-images.githubusercontent.com/3798226/69832708-1ea3c180-1230-11ea-8ce6-bac417069057.png)
- [x] Allow accessing a specific tab of the group. [Screenshot](https://user-images.githubusercontent.com/3798226/69832715-1f3c5800-1230-11ea-8441-5ea8284dac2c.png)
- [x] Allow closing a specific tab of the group. [Screenshot](https://user-images.githubusercontent.com/3798226/69832703-1e0b2b00-1230-11ea-8de2-cbb41efffe54.png)
- [x] Allow adding a new tab in the group. [Screenshot](https://user-images.githubusercontent.com/3798226/69824620-aa0b5b80-120c-11ea-9319-903f28f2fee2.png)
- [x] Show current active tab in list. [Screenshot](https://user-images.githubusercontent.com/3798226/69824125-2ef57580-120b-11ea-9806-d481f546548a.png)

### Additions
- [x] Toggle popup view on click in the toolbar button or with existing keyboard shortcut.
- [x] Light and dark theme support. [Screenshot dark](https://user-images.githubusercontent.com/3798226/69832717-1fd4ee80-1230-11ea-8b5a-bd7b700b1247.png) [Screenshot light](https://user-images.githubusercontent.com/3798226/69832719-1fd4ee80-1230-11ea-8a03-00a740aef9c8.png)
- [x] Nearly full keyboard navigation within the popup.
- Open popup view with keyboard shortcut.
- Navigate with arrow-keys of tab-key through the view.
[VIDEO: video-keyboard-navigation.zip](https://github.com/projectdelphai/panorama-tab-groups/files/3918618/video-keyboard-navigation.zip)
- [x] Add option to choose between existing _freeform view_ and new _popup view_ in the settings menu. [Screenshot](https://user-images.githubusercontent.com/3798226/69832711-1ea3c180-1230-11ea-9ec2-964c594e80bb.png)
- [x] Hide none related options for each view in the settings menu.
- [x] Ensure a simple freeform layout is create in case the user decides to switch from popup view to freeform view.

## Open Tasks
- [x] Check compatibility to [lower Firefox Versions](https://sourceforge.net/projects/portableapps/files/Mozilla%20Firefox%2C%20Portable%20Ed./).
- [x] Add function to allow move tab to another group - work in progress
- [ ] Check popup view for users with large legacy tab groups.
- [ ] Check for bugs when switch between the usage of freeform view and popup view.
- [x] Check compatibility with backups. (since no new tab/group properties was defined, it should be fine)
- [x] Set popup view with dark theme as default for the extension in v1.
- [x] Polish search (list tabs by group, add proper "not found", restore groups when removing search query).
- [ ] When removing a group, decide what's happening when the last group is removed.
- [ ] When removing a group, update the group list to highlight the new active group.
- [ ] When adding a group, a new tab is opened and the group detail frame is shown with active group name editing. But the focus is lost. Find a way to prevent this.
- [ ] Update new translations.
- [ ] Handle pinned tabs (fix active group highlight, put tabs in separate/none-moveable last group?).
- [ ] Async more things while render stuff.
- [x] Save edited group name on input blur.
- [ ] Ensure tabs of context menu "send to group" are correctly attached.

### CODE REVIEW

**Comment by projectdelphai** [comment]
. . . This looks amazing. Will probably take a long time to merge and confirm but it'll be perfect for a Winter release and it'll be my priority.

**Comment by vaxul** [comment]
Take your time and don't rush. I hope there is no breaking stuff in it. 🙂

**Comment by vaxul** [comment]
I tested this new view in:
* ✅ Firefox Developer Edition v72.x Beta while developing
* ✅ Firefox v71.0 while developing
* ✅ Firefox v70.0 while developing
* ✅ Firefox v65.0
* ❕ Firefox ESR v60.9.0
** Not compatible caused by "title in toolbar icon"-feature:
```
Error: Type error for parameter details (Unexpected property "windowId") for browserAction.setTitle.  background.js:353:5
```
** Little glitch: drag-state isn't removed when dropped

**Comment by vaxul** [comment]
I thought about a function to allow move a tab to another group, but this is already available with the context menu for tabs.
But I found a bug, which doesn't hide the tab when moving the current active tab to another group. I look into it.

**Comment by vaxul** [comment]
@projectdelphai 
Any plans when you could review this PR?

**Comment by vaxul** [comment]
@projectdelphai 
Any signs of you?

**Comment by projectdelphai** [comment]
I'm alive, work's just been piling up these past couple weeks. Slotted out this weekend to take a look at all the pull requests

**Comment by projectdelphai** [comment]
Having trouble getting this pull request to work. It looks amazing but I'm getting an error trying to delete groups:
image

and the group won't delete. Trying to figure out if it's me or not. That error message is less than helpful lol. I'm on linux using Firefox 73 running web-ext to test the addon. 

Also noticing then when I create groups in popup view then switch to freeform, the created groups (and any names I set in popup view) don't get transferred.

**Comment by vaxul** [comment]
This is wierd. 🤔 probably some case with old group data.
I will look into it.

**Comment by vaxul** [comment]
> NS_ERROR_NOT_AVAILABLE (0x80040111) An operation could not be completed because some other necessary component or resource was not available. 

https://developer.mozilla.org/en-US/docs/Mozilla/Errors

🤔

**Comment by vaxul** [comment]
I tested a fresh installation of Ubunu 18 LTS with Firefox 73. This setup is working as expected. I can't reproduce your error. Do you have any idea on how to reproduce it?

**Comment by projectdelphai** [comment]
I'm almost positive that it's my installation of Arch Linux that's messing
with it. I just want to fix it to ensure that it doesn't happen again (and
possibly provide help for others who might have it). Then I'll retest and
merge.

**Comment by vaxul** [comment]
> Also noticing then when I create groups in popup view then switch to freeform, the created groups (and any names I set in popup view) don't get transferred.

This is "fixed". I order a reload of the freeform view, when switching the views, so that the changes are directly visible.

**Comment by dorkbox** [comment]
So when will this be merged?

**Comment by rboarman-sc** [comment]
bump

**Comment by vaxul** [comment]
@projectdelphai would you be able to review this change again?

@dorkbox , @rboarman-sc , would use please help with testing of the code from this pull request?

**Comment by dorkbox** [comment]
@vaxul Sure, i can test. How do I build/install it?

**Comment by vaxul** [comment]
1. first backup you current Firefox profile f.e. with [Mozbackup](http://mozbackup.jasnapaka.com/)
1. (optional) export a backup from your tab groups within the PTG settings
1. open [https://github.com/vaxul/panorama-tab-groups/tree/feature/%23131_add_popup_view](https://github.com/vaxul/panorama-tab-groups/tree/feature/%23131_add_popup_view)
1. click on the green button 'Clone or download' and choose 'Download Zip'.
1. Extract the Zip in your preferred location.
1. disable you current PTG Add-on.
1. open the address `about:debugging#/runtime/this-firefox` in Firefox
1. expand 'temporary extensions'
1. click 'Load Temporary Add-on...'
1. within the file browser navigate to your previously extracted folder and select the file `src/manifest.json` 
=> you now running the development version of PTG
1.  open PTG and go the the settings
1. switch 'View' to 'Popup' and choose between light and dark 'Theme' 
=> when clicking the PTG icon, the popup should be open
1. Happy testing 😀

❗ Please look into the initial post for details about the development state. I listed all, which should work and some parts which doesn't work (yet). When reporting a bug, please share details about your setup.

**Comment by rboarman-sc** [comment]
> 
> 
> @projectdelphai would you be able to review this change again?
> 
> @dorkbox , @rboarman-sc , would use please help with testing of the code from this pull request?

Yes, I have installed and will test. Thank you.

**Comment by rboarman** [comment]
@vaxul I've been running the extension on Windows 10, FireFox v75.0. The only issue I've encountered is that, on occasion, the count of the number of tab groups that displays as a little red number over the icon, is not always accurate. I've also noticed that I've needed to select "Refresh groups" from the "Send to Group" sub-menu a few times. This seems to happen after the computer sleeps and wakes up.

**Pull request merged**
