### PR TITLE
Do not reset group data in restored windows

### PR DESCRIPTION
**Pull request by Qantas94Heavy**
When the user manually restores a window (e.g. by pressing Ctrl+Shift+N), the onCreated event will be called even if the window already contains group data. Add a check to make sure group data is not overwritten in these cases.

Fixes: https://github.com/projectdelphai/panorama-tab-groups/issues/55

### CODE REVIEW

**Comment by vaxul** [comment]
Works. 👍

The group positions get lost after restoring the window. Have looked into this?

**Comment by Qantas94Heavy** [comment]
Interesting, for me when I reopened the window using Ctrl+Shift+N the groups appeared in the same place in the tab groups window, even after moving them. Can anyone else reproduce this?

**Comment by vaxul** [comment]
🤔 I admit it happened not every time. It likely not have to do with this pull request.

**Comment by projectdelphai** [comment]
The positions of the groups if I place them stay in their positions when I Ctrl+Shift+n so it looks fine to me. I did find a bug regarding groups and positions, but it's unrelated to this commit. It's good to merge.

**Pull request merged**
