### PR TITLE
Save theme toggle state in view setting

### PR DESCRIPTION
**Pull request by vaxul**
Currently this method saves only the current theme state from the toggle button. For future enhancement I'd like merge this toggle with the addon settings or for a far future read the theme colors from the browser.

### CODE REVIEW

**Comment by Pablo1107** [comment]
If this makes selecting dark theme persistent, it has to be merged ASAP. haha

**Comment by projectdelphai** [comment]
wow, i don't use the dark theme so I didn't even realize the setting doesn't persist (EVEN in the same session). I've blocked out today for work on this addon so I'll be getting to all the activity and pull requests today!

**Comment by vaxul** [comment]
@projectdelphai Thanks for the merge. Any plans on when to release a bugfix version?

**Comment by projectdelphai** [comment]
so [this milestone](https://github.com/projectdelphai/panorama-tab-groups/milestones) is the next planned one so you can see the goals I had for v0.8.5. However, that was before we got some pretty nice fixes and features merged in. I'm looking into using the arrow keys to jump between tabs and i'll probably push it after that. 

I'll probably push grid layouts til later

**Pull request merged**
