### PR TITLE
Infinite scrolling

### PR DESCRIPTION
**Pull request by animaone**
I think being able to enable/disable infinite scrolling could be a very useful feature.
Actually, I have implemented only permanently enabled scrolling, with click/drag feature.
To test the new feature just grab a group to one of the window borders(right or bottom).

### CODE REVIEW

**Comment by vaxul** [comment]
@animaone 
Thanks for your contribution. Would you please provide your use case?

As your wrote, an option would be nice. Did you need help with this?

**Comment by animaone** [comment]
I think it might be an enhancement to a possible 'group move' use case. Since I am using it in conjunction with the tree-style tabs addon, the screen size is somewhat limited, so infinite scrolling is helping me to position more groups on the screen.

Regarding an option to enable / disable infinite scrolling, I think it may be useful for any user who wants to limit the number of possible groups. For me, I prefer infinite scrolling, so I am not planning on implementing this option, I ask you to consider leaving it permanently enabled.

Thank you.

**Comment by vaxul** [comment]
I tested it. It works as expected.

I'm with you. This should be enabled permanently. In this case you could cleanup the commented code.

**Comment by projectdelphai** [comment]
Works fine for me too. I worried that it would conflict with the tiling mode but it switches seamlessly between tiling and freeform. Good job.

**Pull request merged**
