### PR TITLE
Enhance toolbar options

### LINKED ISSUE #46: Sidebar
I preferred the old sidebar position on the side since it wasted less space, so it would be useful to have an option to select the sidebar position (Top, Bottom, Left or Right).

### PR DESCRIPTION
**Pull request by vaxul**
* resolve #46 by adding an option to position toolbar top/right/bottom/left
* move theme setting into options dialog

### CODE REVIEW

**Comment by projectdelphai** [comment]
I won't have time to look at this until later but I think it might not be a bad idea to keep the option to toggle the theme in the view.css along with keeping it in options. I know when I've wanted to switch to the dark theme, it's been a lot easier to just click it in the view then switching to the addon settings.

**Comment by vaxul** [comment]
I tought it more as a UI clutter, since it is most of the time a one time option.

I will add today a little migration script, so that the old setting isn't lost after updating. 

For the future I'd like to read the current theme of the browser and set the theme initially like it and allow switching. I've tried it, but it doesn't work.

Do you know how to notify the user about changes after updates? I saw in the wild, that addons open a new tab which holding the changelog. Sometimes a dedicated addon tab, other times an external link to a website. I think if we write proper release notes here at github (f.e. like Twitter Bootstrap) we could open a new tab to the latest release note after an update. So user learn about the new options.

**Comment by projectdelphai** [comment]
Really good job, I think the toolbar moving is really nice and what a lot of people might want. I mostly moved the toolbar to the top so that we could one day have a search function to search tabs, however, since it's not implemented yet, giving people the option to move the toolbar is better.

Also I generally don't like adding in code for something so small as keeping the theme change since they could easily just change it to whatever htey want themselves. However, since we're going to delete that code soon anyways, no reason not to include it. Thanks for all the hard work!

**Comment by vaxul** [comment]
Thanks for the merge.

> Also I generally don't like adding in code for something so small as keeping the theme change since they could easily just change it to whatever htey want themselves. However, since we're going to delete that code soon anyways, no reason not to include it. Thanks for all the hard work!

Could you please explain this part a bit more? I think I don't understand. 

I'm beside the work normally a user of the https://vivaldi.com/ browser. I really like the spirit of give user a good default, but leave power users the choice with more options.

**Comment by projectdelphai** [comment]
I meant that I usually don't like to add code that is unnecessary. In this case, not including the migration script wouldn't break anything, it would just revert back to light mode and the user would just go to the options page and change it again. But considering it's a small amount of code and it'll get removed in the next couple of versions, it's not that big a deal. Thanks for the work :)

**Pull request merged**
